### PR TITLE
Fix card styling 

### PR DESCRIPTION
**Pull request by anirudhsudhir**
Solves issue #25 

I've given the current leader a thicker border and different colours, while the rest of the participants have their border and font styled with official Hacktoberfest colours

### CODE REVIEW

**Comment by anuragrao04** [comment]
Can you please add a blur rather than opacity. Improve text readability.

**Comment by anirudhsudhir** [comment]
@anuragrao04 Is it fine now? I improved text and image opacity

**Comment by anuragrao04** [comment]
it looks better but please try to implement a blur instead of opacity

**Comment by anirudhsudhir** [comment]
I've switched to a blurred background now. Is it fine or should i modify the blur level?

**Comment by anuragrao04** [comment]
yepp this works!

**Comment by anuragrao04** [comment]
!bounty 40

**Pull request closed without merging**
